name = "awesome"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/. 

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
simplifile = ">= 2.0.0 and < 3.0.0"
gleam_httpc = "~> 2.1"
tom = ">= 1.0.0 and < 2.0.0"
sqlight = "~> 0.9"
gleam_http = "~> 3.5"
argv = ">= 1.0.2 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
