name = "cake_shork"
description = "ğŸ‚Cake ğŸ¦­MariaDB and ğŸ¬MySQL adapters which pass PreparedStatements to the shork library for execution written in Gleam."
repo_url = "https://github.com/inoas/gleam-cake-shork"
category = ""
