name = "cake_pog"
description = "ğŸ‚Cake ğŸ˜PostgreSQL adapter which passes PreparedStatements to the pog library for execution written in Gleam."
docs_url = "https://hexdocs.pm/cake_pog/"
repo_url = "https://github.com/inoas/gleam-cake-pog"
category = ""
