name = "cake_gmysql"
description = "ğŸ‚Cake ğŸ¦­MariaDB and ğŸ¬MySQL adapters which which pass PreparedStatements to the gmysql library for execution written in Gleam."
repo_url = "https://github.com/inoas/gleam-cake-gmysql"
category = ""
