name = "cake_gleam_pgo"
description = "ğŸ‚Cake ğŸ˜PostgreSQL adapter which which passes PreparedStatements to the gleam_pgo library for execution written in Gleam."
docs_url = "https://hexdocs.pm/cake_gleam_pgo/"
repo_url = "https://github.com/inoas/gleam-cake-gleam_pgo"
category = ""
