name = "dahlia"
description = "Dahlia a simple text formatting package, inspired by the game Minecraft."
docs_url = "https://hexdocs.pm/dahlia/"
repo_url = "https://github.com/dahlia-lib/dahlia-gleam"
category = ""
