name = "defangle"
description = "Defangle is a Gleam library for defanging URLs, Emails, and IP addresses making them safe to share."
repo_url = "https://github.com/brittonhayes/defangle"
category = ""
