name = "file_streams"
description = "Gleam library that provides access to native Erlang binary file streams."
docs_url = "https://hexdocs.pm/file_streams/"
repo_url = "https://github.com/richard-viney/file_streams"
category = ""
