name = "flash"
description = "Gleam package enabling structured logging in both Erlang and JavaScript environments"
docs_url = "https://hexdocs.pm/flash/"
repo_url = "https://github.com/larzconwell/flash"
category = ""
