name = "fluoresce"
description = "A fun type-tetris Gleam library for algebraic effects, the Continuation monad, and classical logic types."
repo_url = "https://github.com/RyanBrewer317/fluoresce"
category = ""
