name = "gleam_zlists"
description = "A library for working with lazy lists in Gleam"
docs_url = "https://hexdocs.pm/gleam_zlists/"
repo_url = "https://github.com/mrdimosthenis/gleam_zlists"
category = ""
