name = "go_over"
description = "A tool to audit Erlang & Elixir dependencies, to make sure your gleam projects really sparkle! âœ¨"
docs_url = "https://hexdocs.pm/go_over/"
repo_url = "https://github.com/bwireman/go-over"
category = "Project Tooling"
