name = "howdy_uuid"
description = "A library for Gleam to parse UUIDs. This is a slightly modify version of gleam_uuid, to work with the latest version of gleam"
docs_url = "https://hexdocs.pm/howdy_uuid/"
repo_url = "https://github.com/mikeyjones/howdy_uuid"
category = ""
