name = "kirala_markdown"
description = "Markdown parser and html renderer written in Gleam language both Erlang and Javascript target."
repo_url = "https://github.com/Yasuo-Higano/kirala_markdown"
category = ""
