name = "p5js_gleam"
description = "A simple game library providing p5.js bindings for Gleam in a functional style to make basic games and animations. Heavily inspired by the Racket library 2htdp/universe"
docs_url = "https://hexdocs.pm/p5js_gleam/"
repo_url = "https://github.com/Acepie/p5js_gleam"
category = ""
