name = "wisp_kv_sessions"
description = "wisp_kv_sessions is a key-value session management library for [Wisp](https://gleam-wisp.github.io/wisp/), inspired by the Rust crate [tower sessions](https://docs.rs/tower-sessions/latest/tower_sessions/#). This library allows you to manage user sessions with ease, storing session data in a simple key-value store."
docs_url = "https://hexdocs.pm/wisp_kv_sessions/"
repo_url = "https://github.com/MaxHill/wisp_kv_sessions"
category = ""
